core/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('team/', views.team, name='team'),
    path('contact/', views.contact, name='contact'),
    path('gestions/', include('main_apps.gestions.urls')),
    path('comptes/', include('main_apps.comptes.urls')),
    path('assistance/', include('main_apps.Assistance_Technique.urls')),
    path('communication/', include('main_apps.Communication.urls')),
    path('comptabilite/', include('main_apps.Comptabilite.urls')),
    path('paiement/', include('main_apps.Paiement.urls')),
    path('statistique/', include('main_apps.Statistique.urls')),
    path('vote/', include('main_apps.Vote.urls')),
    path('Communaute/', include('main_apps.Communaute.urls')),
]

main_apps/Assistance_Technique/urls.py
from django.urls import path
from . import views

app_name = "Assistance_Technique"

urlpatterns = [
    path('', views.Assistant_Technique_views, name='Assistant_Technique'),
]

main_apps/Communaute/urls.py
from django.urls import path
from . import views

app_name = "Communaute"

urlpatterns = [
    
    path('', views.Communaute_View, name='communaute'),
    
]

main_apps/Communication/urls.py
from django.urls import path
from . import views

app_name = "Communication"
urlpatterns = [
    path('', views.Communication_View, name='Communication'),
]

main_apps/Comptabilite/urls.py
from django.urls import path
from . import views

app_name = "Comptabilite"
urlpatterns = [
    path('', views.Comptabilite_View, name='Comptabilite')
]

main_apps/Paiement/urls.py
from django.urls import path
from . import views

app_name = "Paiement"
urlpatterns = [
    path('', views.Paiement_View, name='paiement')
]

main_apps/Statistique/urls.py
from django.urls import path
from . import views

app_name = "Statistique"
urlpatterns = [
    path('', views.Statistique_View, name='statistique')
]

main_apps/Vote/urls.py
from django.urls import path
from . import views

app_name = "Vote"
urlpatterns = [
    path('', views.Vote_View, name='vote_urls')
]

main_apps/comptes/urls.py
from django.urls import path
from . import views

app_name = 'comptes'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),         
    
]

main_apps/gestions/urls.py
from django.urls import path
from . import views

app_name = 'gestions'

urlpatterns = [
    path('', views.main_dash, name='home'),
    path('membre/', views.membre, name='membre'),
]

main_apps/Communaute/models.py
from django.db import models

# Create your models here.

main_apps/Paiement/models.py
from django.db import models

# Create your models here.

main_apps/Statistique/models.py
from django.db import models

# Create your models here.

main_apps/Vote/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def team(request):
    return render(request, 'team.html')


def contact(request):
    return render(request, 'contact.html')

main_apps/Communaute/views.py
from django.shortcuts import render

# Create your views here.
def Communaute_View(request):
    return render(request, 'Communaute/communaute.html')

main_apps/Communication/views.py
from django.shortcuts import render

# Create your views here.

def Communication_View(request):
    return render(request, 'Communication/Communication.html')

main_apps/Comptabilite/views.py
from django.shortcuts import render

# Create your views here.
def Comptabilite_View(request):
    return render(request, 'Comptabilite/Comptabilite.html')

main_apps/Paiement/views.py
from django.shortcuts import render

# Create your views here.
def Paiement_View(request):
    return render(request, 'Paiement/paiement.html')

main_apps/Statistique/views.py
from django.shortcuts import render

# Create your views here.
def Statistique_View(request):
    return render(request, 'Statistique/Statistique.html')

main_apps/Vote/views.py
from django.shortcuts import render

# Create your views here.
def Vote_View(request):
    return render(request, 'Vote/vote.html')

main_apps/comptes/views.py
from django.shortcuts import render

# Create your views here.
def login_view(request):
    return render(request, 'comptes/signin.html')

def register(request):
    return render(request, 'comptes/signup.html')

def logout(request):
    return render(request, 'comptes/logout.html')

main_apps/gestions/views.py
from django.shortcuts import render

# Create your views here.

def main_dash(request):
    
    return render(request,'gestions/home.html')


def membre(request):
    
    return render(request,'gestions/membre.html')

templates/comptes/reset-password.html
<!DOCTYPE html><html lang="en" class="cmmz3">
<!-- Mirrored from preview.cruip.com/stellar/reset-password.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 02 May 2024 04:42:19 GMT -->
<head>
    <meta charset="utf-8">
    <title>Stellar HTML Demo - Reset Password</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="css/vendors/aos.css" rel="stylesheet">
    <link href="style.css" rel="stylesheet">
<script defer data-domain='preview.cruip.com,rollup.cruip.com' src='https://plausible.cruip.com/js/script.js'></script></head>

<body class="c4f4x cupde cs2bp c55gg czrq6">

    <!-- Page wrapper -->
    <div class="crm2f cbvce cxgh5 cfebz c4agq">
    
        <main class="c9wgl">
    
            <section class="c27r3">
    
                <!-- Illustration -->
                <div class="c3sb3 c2vxt cutr4 c3x17 cs26b ca5ue c7upq cpsfp ch67j" aria-hidden="true">
                    <img src="images/auth-illustration.svg" class="cbdyn" width="1440" height="450" alt="Page Illustration">
                </div>
    
                <div class="co3q6 c27r3 csm51 csya4 ccyhi">
                    <div class="c9eon cz17m cifrc cp02i">
    
                        <!-- Page header -->
                        <div class="cw9su c80wd csya4 cifrc">
                            <!-- Logo -->
                            <div class="crdb2">
                                <a class="cwban" href="index-2.html">
                                    <div class="c3d7q cegg3 cn2kl cy8oh c1mpe ccqfq csqqr c2sao cck9i ctnsh c27r3 cn544 c4agq cm0fl c0ho4">
                                        <img class="c27r3" src="images/logo.svg" width="42" height="42" alt="Stellar">
                                    </div>
                                </a>
                            </div>
                            <!-- Page title -->
                            <h1 class="cc7gh ccqrz cx8zw c6df8 cfcmr ctwez c4zau">Reset your password</h1>
                        </div>
    
                        <!-- Form -->
                        <div class="c1omz csya4">
    
                            <form>
                                <div class="cavuv">
                                    <div>
                                        <label class="cit3o ccqx1 cvdvu cxz3l c986a" for="email">Email</label>
                                        <input id="email" class="c6i2l ca0gw" type="email" required="">
                                    </div>
                                </div>
                                <div class="ckwat">
                                    <button class="ckbyi cw2sl cnur3 cgpyo cvdvu ca0gw cq2yg cyijk">
                                        Reset Password <span class="c9pof c406y cxxyq ckj0y cx3jz cgi3a cqzh1">-&gt;</span>
                                    </button>
                                </div>
                            </form>
    
                        </div>
    
                    </div>
                </div>
    
            </section>
    
        </main>
    
    </div>

    <script src="js/vendors/alpinejs.min.js" defer=""></script>
    <script src="js/vendors/aos.js"></script>
    <script src="js/main.js"></script>



<script>console.log("%cImportant!", "color: blue; font-size: x-large");console.log("%cThe page you are viewing is for demo purposes only. CSS and HTML have been minified and class names have been shortened to improve the page load time. Download our templates from https://cruip.com/ 😉", "font-size: large");</script><script>const pagesList = [{"name":"Home","url":"https://preview.cruip.com/stellar/index.html","active":false},{"name":"About","url":"https://preview.cruip.com/stellar/about.html","active":false},{"name":"Integrations","url":"https://preview.cruip.com/stellar/integrations.html","active":false},{"name":"Integration Post","url":"https://preview.cruip.com/stellar/integrations-single.html","active":false},{"name":"Pricing","url":"https://preview.cruip.com/stellar/pricing.html","active":false},{"name":"Customers","url":"https://preview.cruip.com/stellar/customers.html","active":false},{"name":"Customer Post","url":"https://preview.cruip.com/stellar/customer.html","active":false},{"name":"Changelog","url":"https://preview.cruip.com/stellar/changelog.html","active":false},{"name":"Sign in","url":"https://preview.cruip.com/stellar/signin.html","active":false},{"name":"Sign up","url":"https://preview.cruip.com/stellar/signup.html","active":false},{"name":"Reset password","url":"https://preview.cruip.com/stellar/reset-password.html","active":true}];if(window != top){window.parent.postMessage(pagesList, "https://cruip.com/")};</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v55bfa2fee65d44688e90c00735ed189a1713218998793" integrity="sha512-FIKRFRxgD20moAo96hkZQy/5QojZDAbyx0mQ17jEGHCJc/vi0G2HXLtofwD7Q3NmivvP9at5EVgbRqOaOQb+Rg==" data-cf-beacon='{"rayId":"87d557ee4c8c60c5","version":"2024.4.1","r":1,"token":"59cc17d45d734f9ba118c63036ab1b84","b":1}' crossorigin="anonymous"></script>
</body>
<!-- Mirrored from preview.cruip.com/stellar/reset-password.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 02 May 2024 04:42:19 GMT -->
</html>

templates/comptes/signin.html
{% extends "_base2.html" %}
{% load static %}
{% block content %}

    <!-- Page wrapper -->
    <div class="crm2f cbvce cxgh5 cfebz c4agq">

        <main class="c9wgl">

            <section class="c27r3">
            
                <!-- Illustration -->
                <div class="c3sb3 c2vxt cutr4 c3x17 cs26b ca5ue c7upq cpsfp ch67j" aria-hidden="true">
                    <img src="{% static "accounts/images/auth-illustration.svg" %}" class="cbdyn" width="1440" height="450" alt="Page Illustration">
                </div>
            
                <div class="co3q6 c27r3 csm51 csya4 ccyhi">
                    <div class="c9eon cz17m cifrc cp02i">

                        <!-- Page header -->
                        <div class="cw9su c80wd csya4 cifrc">
                            <!-- Logo -->
                            <div class="crdb2">
                                <a class="cwban" href="index-2.html">
                                    <div class="c3d7q cegg3 cn2kl cy8oh c1mpe ccqfq csqqr c2sao cck9i ctnsh c27r3 cn544 c4agq cm0fl c0ho4">
                                        <img class="c27r3" src="{% static "accounts/images/logo.svg" %}" width="42" height="42" alt="Stellar">
                                    </div>
                                </a>
                            </div>
                            <!-- Page title -->
                            <h1 class="cc7gh ccqrz cx8zw c6df8 cfcmr ctwez c4zau">Ouvrez votre session</h1>
                        </div>
                        
                        <!-- Form -->
                        <div class="c1omz csya4">

                            <form>
                                <div class="cavuv">
                                    <div>
                                        <label class="cit3o ccqx1 cvdvu cxz3l c986a" for="email">Email</label>
                                        <input id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required="">
                                    </div>
                                    <div>
                                        <div class="cm7bi c4agq">
                                            <label class="cit3o ccqx1 cvdvu cxz3l c986a" for="password">Password</label>
                                            <a class="clu19 c3fbv cx3jz ccqx1 cgi3a cqxsj cvdvu cmzyi" href="reset-password.html">Forgot?</a>
                                        </div>
                                        <input id="password" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" autocomplete="on" required="">
                                    </div>
                                </div>
                                <div class="ckwat">
                                    
                                        <button class="ckbyi cw2sl cnur3 cgpyo cvdvu ca0gw cq2yg cyijk">
                                            <a href="{% url 'gestions:home' %}"> Sign In <span class="c9pof c406y cxxyq ckj0y cx3jz cgi3a cqzh1">-&gt;</span></a>
                                        </button>
                                    
                                </div>
                            </form>

                            <div class="cw9su c3os2">
                                <div class="cmuyi cvdvu">
                                    Vous avez pas de Compte ? <a class="clu19 c3fbv cx3jz ccqx1 cgi3a cqxsj" href="{% url "comptes:register" %}">Sign up</a>
                                </div>
                            </div>

                            <!-- Divider -->
                            <div class="c2sao cuqgt c4agq">
                                <div class="czyxl ckogj cygn6 c9wgl" aria-hidden="true"></div>
                                <div class="cgzoy cvdvu c18x8">or</div>
                                <div class="czyxl ckogj cawyw c9wgl" aria-hidden="true"></div>
                            </div>
                            
                            <!-- Social login -->
                            <div class="cujq3 c4agq">
                                <button class="c3d7q c272e cegg3 c8isz c0z2s c1mpe ccqfq cit3o cx3jz cgi3a cqxsj c27r3 ca0gw cq2yg cyijk cdfq1">
                                    <span class="c27r3">
                                        <span class="cmmna">Continue with Twitter</span>
                                        <svg class="cm1cr" xmlns="http://www.w3.org/2000/svg" width="14" height="12">
                                            <path d="m4.34 0 2.995 3.836L10.801 0h2.103L8.311 5.084 13.714 12H9.482L6.169 7.806 2.375 12H.271l4.915-5.436L0 0h4.34Zm-.635 1.155H2.457l7.607 9.627h1.165L3.705 1.155Z"></path>
                                        </svg>
                                    </span>
                                </button>
                                <button class="c3d7q c272e cegg3 c8isz c0z2s c1mpe ccqfq cit3o cx3jz cgi3a cqxsj c27r3 ca0gw cq2yg cyijk cdfq1">
                                    <span class="c27r3">
                                        <span class="cmmna">Continue with GitHub</span>
                                        <svg class="cm1cr" xmlns="http://www.w3.org/2000/svg" width="16" height="15">
                                            <path d="M7.488 0C3.37 0 0 3.37 0 7.488c0 3.276 2.153 6.084 5.148 7.113.374.094.468-.187.468-.374v-1.31c-2.06.467-2.527-.936-2.527-.936-.375-.843-.843-1.124-.843-1.124-.655-.468.094-.468.094-.468.749.094 1.123.75 1.123.75.655 1.216 1.778.842 2.153.654.093-.468.28-.842.468-1.03-1.685-.186-3.37-.842-3.37-3.743 0-.843.281-1.498.75-1.966-.094-.187-.375-.936.093-1.965 0 0 .655-.187 2.059.749a6.035 6.035 0 0 1 1.872-.281c.655 0 1.31.093 1.872.28 1.404-.935 2.059-.748 2.059-.748.374 1.03.187 1.778.094 1.965.468.562.748 1.217.748 1.966 0 2.901-1.778 3.463-3.463 3.65.281.375.562.843.562 1.498v2.059c0 .187.093.468.561.374 2.996-1.03 5.148-3.837 5.148-7.113C14.976 3.37 11.606 0 7.488 0Z"></path>
                                        </svg>
                                    </span>
                                </button>
                            </div>

                        </div>

                    </div>
                </div>

            </section>

        </main>

    </div>

{% endblock content %}